# Generated by Django 5.0.4 on 2024-05-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_category_options_rename_title_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
